name: design_system
description: "A new Flutter package project."
version: 1.0.0
homepage: design_system
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.3.0
  auto_size_text: ^3.0.0
  device_info_plus: ^12.3.0
  firebase_core: ^4.5.0
  firebase_crashlytics: ^5.0.8
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  get:
    git:
      url: https://github.com/Aniketkhote/getx.git
      ref: 59435ba761112110118457b9443f901f19fbfab3
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  desktop_drop: ^0.7.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  isar: ^3.1.0+1
  keyboard_actions: ^4.2.1
  list_picker:
    git:
      url: https://github.com/SamuelsonPajeu/list_picker-ptbr.git
  local_auth: ^3.0.1
  mask_text_input_formatter: ^2.9.0
  material_symbols_icons: ^4.2906.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  storybook_flutter_workspace:
    git:
      url: https://github.com/ookami-kb/storybook_flutter.git
  universal_platform: ^1.1.0
  fl_chart: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: pt
  locales:
    - pt

flutter:
  uses-material-design: true

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/notosans/NotoSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/notosans/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Black.ttf
        - asset: assets/fonts/notosans/static/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Bold.ttf
        - asset: assets/fonts/notosans/static/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/notosans/static/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Italic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Light.ttf
        - asset: assets/fonts/notosans/static/NotoSans-LightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Medium.ttf
        - asset: assets/fonts/notosans/static/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Regular.ttf
        - asset: assets/fonts/notosans/static/NotoSans-SemiBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans-Thin.ttf
        - asset: assets/fonts/notosans/static/NotoSans-ThinItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Black.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-BlackItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Bold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-BoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-ExtraBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-ExtraLight.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-ExtraLightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Italic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Light.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-LightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Medium.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-MediumItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-Thin.ttf
        - asset: assets/fonts/notosans/static/NotoSans_Condensed-ThinItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Black.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-BlackItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Bold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-BoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-ExtraBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-ExtraLight.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Italic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Light.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-LightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Medium.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-MediumItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Regular.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-SemiBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-Thin.ttf
        - asset: assets/fonts/notosans/static/NotoSans_ExtraCondensed-ThinItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Black.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-BlackItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Bold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-ExtraLight.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Italic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Light.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Medium.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-Thin.ttf
        - asset: assets/fonts/notosans/static/NotoSans_SemiCondensed-ThinItalic.ttf